services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=sqlite
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=database
      - CACHE_STORE=database
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    volumes:
      - ./database:/var/www/html/database
      - ./storage:/var/www/html/storage
    restart: unless-stopped
